#' Show importance of features in a model
#' 
#' Create a \code{data.table} of the most important features of a model. 
#' 
#' @param feature_names names of each feature as a \code{character} vector. Can be extracted from a sparse matrix (see example). If model dump already contains feature names, this argument should be \code{NULL}.
#' @param filename_dump generated by the \code{xgb.dump} function. This is used to count the number of times each variable has been used for splitting all the trees.
#'
#' @return A \code{list} of the features used in the model with their relative importance in the model.
#'
#' @details 
#' This function is for both linear and tree models.
#' 
#' \code{list} is returned by the function. 
#' 
xgb.importance <- function(feature_names, filename_dump) {
  fmap <- list()
  nmap <- list()
  sapply(seq_along(feature_names),
    function(x) {
      fmap[[feature_names[x]]] <<- 0
      nmap[[x]] <<- feature_names[x]
     })
  total <- 0
  sapply(readLines(filename_dump),
    function(x) {
      m <- regexec("\\[f.*\\]", x)
      p <- regmatches(x, m)
      if (length(p[[1]]) > 0) {
        splits <- strsplit(sub("\\]", "", sub("\\[f", "", p[[1]])), "<")[[1]]
        fmap[[nmap[[as.integer(splits[1]) + 1]]]] <<- fmap[[nmap[[as.integer(splits[1]) + 1]]]] + 1
        total <<- total + 1
        }
    })                                                                                           
  stopifnot(total > 0)
  lapply(fmap, function(x) x / total * 100)
}

